apiVersion: v1
kind: Service
metadata:
  name: bountifulbytes
spec:
  selector:
    app: bountifulbytes
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 32100
