name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: containers/app.Dockerfile
          push: true
          tags: jdubedition/bountifulbytes-app:${{ github.sha }},jdubedition/bountifulbytes-app:latest

      - name: Image digest/tag
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Pulumi
        uses: pulumi/action-install-pulumi-cli@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
        working-directory: infrastructure/pulumi-k8s

      # Set the kubeconfig file from Github secret
      - run: 'echo "$KUBE_CONFIG" | base64 --decode > kubeconfig'
        shell: bash
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - uses: pulumi/actions@v3
        with:
          command: up
          work-dir: infrastructure/pulumi-k8s
          stack-name: dev-app
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          KUBECONFIG: /home/runner/work/bountifulbytes/bountifulbytes/kubeconfig
          APP_IMAGE: jdubedition/bountifulbytes-app:${{ github.sha }}
